version: "3.7"
services:
    postgresql:
      image: postgres:latest
      restart: always
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - 54320:5432
      volumes:
        - .:/var/www/html
        - postgres_data:/var/lib/postgresql/data
      working_dir: /var/www/html

    pgadmin:
        image: dpage/pgadmin4:4.18
        restart: always
        environment:
          PGADMIN_DEFAULT_EMAIL: postgres
          PGADMIN_DEFAULT_PASSWORD: postgres
          PGADMIN_LISTEN_PORT: 80
        ports:
        - "8035:80"
        volumes:
        - postgres_data:/var/lib/postgresql/data
        links:
        - postgresql

    redis:
      image: redis:alpine
      expose:
        - 6379

    mailhog:
      image: mailhog/mailhog
      ports: 
        - 1021:1025
        - 8021:8025

    web:
      build: ./resources/docker/aws
      ports:
        - 8080:80
      volumes:
        - .:/var/www/html
      links:
        - php

    php:
      build: ./resources/docker/php
      ports:
        - 9000
      volumes:
        - .:/var/www/html
      links:
        - redis
        - postgresql
        - mailhog
      depends_on:
        - redis
        - postgresql
        - mailhog

    sheets:
      build: ./resources/docker/sheets
      links:
        - redis
      expose:
        - "3000"
      volumes:
        - .:/usr/src/app


volumes:
    postgres_data:

